[package]
name = "simple_shadowing"
version = "0.1.0"
authors = ["Anum Essani <essanianum@gmail.com>"]
edition = "2018"
description = "shadow procedure"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
